# Generated by Django 3.1.6 on 2021-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='homeimage/')),
                ('title', models.CharField(max_length=100)),
                ('descrip', models.TextField(max_length=200)),
                ('link', models.URLField(blank=True)),
            ],
        ),
    ]
